version: '3.7'
services:
    dashboard:
        build:
            context: ./dashboard
            target: DEV
        ports:
            - "80:80"
        networks:
            - orange

    auth:
        build:
            context: ./auth
            target: DEV
        ports:
            - "3000:3000"

        environment: 
            - TEST=true
        networks:
            - orange

    zecq:
        build:
            context: ./zecq
            target: DEV
        ports: 
            - "5000:5000"


        environment: 
            - ENV_NAME=DEV
        env_file:
            - .env
        volumes:
            - ./zecq:/app
        networks:
            - orange


networks:
    orange:
        driver: bridge