version: '3.7'
services:
    auth:
        build:
            context: ./auth
            target: DEV
        ports:
            - "3000:3000"
        networks:
            - orange

    zecq:
        build:
            context: ./zecq
            target: DEV
        ports: 
            - "5000:5000"
        networks:
            - orange


networks:
    orange:
        driver: bridge