version: '3.7'
services:
    auth:
        build:
            context: ./auth
            target: DEV
        ports:
            - "3000:3000"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - orange

    zecq:
        build:
            context: ./zecq
            target: DEV
        ports: 
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://boom:TSSkSXcYoubhE9BYSH6A7QMAd9f5zorr@dpg-ch9js9l269v0obamd27g-a.frankfurt-postgres.render.com:5432/screening

        networks:
            - orange


networks:
    orange:
        driver: bridge