"""empty message

Revision ID: 0204efda3d20
Revises: 
Create Date: 2023-06-24 19:02:12.270655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0204efda3d20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('acceptance',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=None)

    op.execute('ALTER TABLE scenarios ALTER COLUMN acceptance TYPE JSON USING acceptance::JSON')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('acceptance',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=None)

    op.execute('ALTER TABLE scenarios ALTER COLUMN acceptance TYPE TEXT USING acceptance::TEXT')


    # ### end Alembic commands ###
