"""empty message

Revision ID: 163f2c642e45
Revises: e68f38c9dd83
Create Date: 2023-06-20 16:17:04.587723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163f2c642e45'
down_revision = 'e68f38c9dd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
