"""empty message

Revision ID: 33c723bd311e
Revises: f06098932dad
Create Date: 2023-06-25 10:06:38.470040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33c723bd311e'
down_revision = 'f06098932dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_time', sa.Integer(), nullable=True))

        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.drop_column('inform_channels')
        batch_op.drop_column('acceptance')

    op.execute("UPDATE scenarios SET acceptance_time = 0 WHERE acceptance_time IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inform_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('acceptance_time')
    op.drop_column('scenarios', 'acceptance_time')

    # ### end Alembic commands ###
