"""empty message

Revision ID: e68f38c9dd83
Revises: 05d84cfd09ec
Create Date: 2023-06-20 15:13:06.326203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e68f38c9dd83'
down_revision = '05d84cfd09ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=False),
    sa.Column('time', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('phone', postgresql.ARRAY(sa.VARCHAR(length=64)), autoincrement=False, nullable=True),
    sa.Column('email', postgresql.ARRAY(sa.VARCHAR(length=64)), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='settings_pkey')
    )
    # ### end Alembic commands ###
