"""empty message

Revision ID: f1693d98366f
Revises: 33c723bd311e
Create Date: 2023-06-27 18:29:45.149887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1693d98366f'
down_revision = '33c723bd311e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_old')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptanceTime', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('userId', sa.String(), nullable=True))
        batch_op.drop_column('acceptance_time')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acceptance_time', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('userId')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('acceptanceTime')

    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('passwordHash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('users_old',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    # ### end Alembic commands ###
